server {
    listen 80;
    server_name localhost;

    root /home/vaioslasxos/Tutor;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$ {
        add_header Cache-Control "public, no-transform";
        access_log off;
    }
}
