server {
    listen 80;
    server_name localhost;

    root /home/vaioslasxos/Tutor;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Explicitly handle JavaScript files
    location ~* \.js$ {
        add_header Cache-Control "public, no-transform";
        access_log off;
        types {
            application/javascript js;
        }
    }

    # Handle other static files
    location ~* \.(css|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$ {
        add_header Cache-Control "public, no-transform";
        access_log off;
    }

    # Enable CORS for development
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
}
